-- AlterTable
ALTER TABLE `complaints` MODIFY `complaintType` ENUM('BILLING', 'OUTAGE', 'LEAKAGE', 'NO_SUPPLY', 'LOW_PRESSURE', 'METER_ISSUE', 'MISSED_PICKUP', 'OVERFLOW', 'CERTIFICATE', 'GENERAL', 'NEW_CONNECTION', 'LOAD_CHANGE') NOT NULL;
