exports.Department = {
  ELECTRICITY: 'ELECTRICITY',
  GAS: 'GAS',
  WATER: 'WATER',
  WASTE: 'WASTE',
  MUNICIPAL: 'MUNICIPAL',
};

exports.ComplaintType = {
  BILLING: 'BILLING',
  OUTAGE: 'OUTAGE',
  LEAKAGE: 'LEAKAGE',
  NO_SUPPLY: 'NO_SUPPLY',
  LOW_PRESSURE: 'LOW_PRESSURE',
  METER_ISSUE: 'METER_ISSUE',
  MISSED_PICKUP: 'MISSED_PICKUP',
  OVERFLOW: 'OVERFLOW',
  CERTIFICATE: 'CERTIFICATE',
  GENERAL: 'GENERAL',
  LOAD_CHANGE: 'LOAD_CHANGE',
  NEW_CONNECTION: 'NEW_CONNECTION',
};

exports.ComplaintStatus = {
  SUBMITTED: 'SUBMITTED',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
};

exports.Priority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  CRITICAL: 'CRITICAL',
};

exports.PaymentStatus = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};
